### ISSUE TITLE
Request for unbundled code

### ISSUE THREAD

**Issue by omarryhan** [liseda-lab/VOWLMap#1]
Hey,

I'm working on a project that would greatly benefit from the awesome work you've with VOWLMap.
Is it possible you provide the source code that compiled to the js files here: https://github.com/liseda-lab/VOWLMap/tree/main/webvowl_1.1.7/js? I need to make some edits, but it's too hard to understand a file processed by Webpack 😄 

Thanks!

**Comment by cpesquita** [comment]
Dear Omar,

Thank you for your interest in our work. VOWLMap builds on WebVOWL.
You should reach out to the creators of WebVOWL:
https://github.com/VisualDataWeb/WebVOWL

Best regards,


Catia Pesquita
LASIGE, Faculdade de Ciências, Universidade de Lisboa
http://www.di.fc.ul.pt/~catiapesquita/

**Comment by omarryhan** [comment]
Thank you for the quick response Catia.

I am familiar with the original WebVOWL project. I just meant that the code your team uploaded here on Github has gone through a processing phase (bundling by Webpack) that makes the end result hardly editable or extendible by other devs.

In the original WebVOWL project, you'll find both a src directory and the deploy directory. However in the repo, I can only find the contents of the deploy directory.

Thanks again!

**Comment by omarryhan** [comment]
Sorry to bother again Catia @cpesquita 

If you don't mind, can you share with me the email of one of the research assistants who worked with you on this, so I don't take any more of your time. Maybe they can help me better?

I'm working on this project with the [University of Haifa](https://haifa.ac.il) and we greatly appreciate your support!

Best,
Omar
